# Generated by Django 2.1 on 2019-03-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cover', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebook.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readingState', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookInstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebook.BookInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookInstance2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebook.BookInstance')),
                ('proposalID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rebook.Proposal')),
            ],
        ),
        migrations.CreateModel(
            name='TradeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.TradeState'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.User'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.User'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.BookGoals'),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rebook.BookState'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rebook.Publisher'),
        ),
    ]
