# Generated by Django 2.1 on 2019-04-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasNotifications',
            field=models.BooleanField(default=False),
        ),
    ]
