# Generated by Django 2.1 on 2019-04-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0003_auto_20190406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(storage='covers/', upload_to=''),
        ),
    ]
