# Generated by Django 2.1 on 2019-04-06 18:55

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0004_auto_20190406_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/covers'), upload_to=''),
        ),
    ]
