# Generated by Django 2.1 on 2019-04-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0006_auto_20190406_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rebook.Ratings'),
        ),
    ]
