# Generated by Django 2.1 on 2019-04-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0008_auto_20190406_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='numberStars',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
