# Generated by Django 2.1 on 2019-04-07 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0010_auto_20190407_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='rating',
        ),
    ]
