# Generated by Django 2.1 on 2019-04-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0011_remove_bookinstance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='rating',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='rebook.Ratings'),
        ),
    ]
