# Generated by Django 2.1 on 2019-04-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0012_bookinstance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rebook.TradeState'),
            preserve_default=False,
        ),
    ]
