# Generated by Django 2.1 on 2019-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0013_proposal_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10.99, max_digits=10),
            preserve_default=False,
        ),
    ]
