# Generated by Django 2.1 on 2019-04-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0014_bookinstance_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
