# Generated by Django 2.1 on 2019-04-08 13:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rebook', '0016_purchases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/covers'), upload_to=''),
        ),
    ]
